name: Update README.md with recent activity

on:
  schedule:
    # Runs every day at 6:30 PM UTC
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-waka-time-metrics:
    name: Update Readme with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@v5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_TIMEZONE: True
          SHOW_LINES_OF_CODE: True
          SHOW_PROJECTS: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_SHORT_INFO: True
          SHOW_LOC_CHART: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_OS: True
          SHOW_EDITORS: True
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True



  update-readme-with-medium-blog:
    name: Update Readme with Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@ajay.kumar_14"