name: Update README.md with blog posts

on:
  schedule:
    # Runs every day at 6:30 PM UTC
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-medium-blog:
    name: Update Readme with Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@ajay.kumar_14"
